add_newline = false

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"
vicmd_symbol = "[V](bold yellow)"

[battery]
discharging_symbol = "âš¡"

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[cmd_duration]
disabled = true

[directory]
style = "blue"
read_only = " ğŸ”’"
fish_style_pwd_dir_length = 1

[git_branch]
always_show_remote = true


[git_status]
style = "bold yellow"
ahead = "â†‘${count}"
behind = "â†“${count}"
diverged = "â†‘${ahead_count}â‡£â†“${behind_count}"
deleted = "âœ—"
staged = '[+\($count\)](green)'
[line_break]
disabled = true

[nodejs]
symbol = "ğŸ¢"
format = "via [$symbol]($style)"

[package]
disabled = true

[python]
symbol = "ğŸ"
style = "green"
format = 'via [${symbol}(\($virtualenv\))]($style)'
